- name: configure catalogue microservice 
  hosts: catalogue
  become: yes
  tasks:
  - name: disable the default nodejs 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable the nodejs:20 -y
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install the node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: run with non-rootuser because of security
    ansible.builtin.user:
      name: roboshop
      path: /app
      shell: /sbin/nologin

  - name: creating a directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: downloading the catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: now unzipping the downloaded file
    ansible:buitin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies and libraries
    community.general.npm:
      path: /app

  - name: To run our custom microservice we need dot service file
    ansible:builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service  # etc lo systemd ane folder lo system lo ee catalogue.service pedutunnam

  - name: Running the daemon reload because when ever we are making any change's in systemd folder 
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Enable catalogue
    ansible:builtin:service:
      name: catalogue
      enabled: yes

  - name: start catalogue
    ansible:builtin:service:
      name: catalogue
      state: started

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo


  - name: Install mongodb client to run the products 
    ansible:builtin:package:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.kalyanu.xyz --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    
  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0