- name: set up mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo
    ansible.biuiltin.copy:
      src: mongo.repo
      des: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org 
      state: present

  - name: enable and start mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes 

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart the mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted